flaskblog/main/routes.py
from flask import render_template, Blueprint, redirect, url_for, session, request, flash, Markup
from flaskblog import db, sess
from flaskblog.models import QueryT
from sqlalchemy import event
import time
main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    db.create_all()
    queriest = QueryT.query.filter_by(user_id=session.sid)
    try:
        queriest[0]
    except IndexError:
        flash(Markup('''Create a <a href="/queriest/new">new query!</a>'''), 'success')
    page = request.args.get('page', 1, type=int)
    queriest = queriest.order_by(QueryT.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template('home.html', queriest=queriest, active1="active", active2="")


@main.route("/about")
def about():
    #run_shelly()
    return render_template('about.html', title='About', legend='About')


@main.route("/home/all")
def home_all():
    page = request.args.get('page', 1, type=int)
    queriest = QueryT.query.order_by(QueryT.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', queriest=queriest, active1="", active2="active")

flaskblog/queries/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, Markup, session, current_app
from flaskblog import db, sess, mail
from flaskblog.queries.forms import QuerytForm, Email
from flaskblog.models import QueryT, Dictionary, Article
from flaskblog.queries.utils import *
import time
from flaskblog.config import ADMINS
import os

from sqlalchemy import event
from flaskblog import rq
from rq.job import Job
from flask_mail import Message
queries = Blueprint('queries',__name__)


@queries.route("/queriest/new", methods=['GET', 'POST'])
def new_queryt():
    existy = Dictionary.query.filter_by(id=1).first()
    if existy is None:
        def insert_initial_dict():
            #print(os.getcwd())
            dict_file = os.path.join(os.getcwd(), 'flaskblog/static/termin.txt')
            fh = open(dict_file)
            for line in fh:
                #print(1, existy)
                termo = Dictionary(terminology=line)
                db.session.add(termo)
            db.session.commit()

        insert_initial_dict()
    form = QuerytForm()

    if form.validate_on_submit():
        #terms = get_terms(get_pubmed(form.term.data))
        flashed = False
        tempterm = form.term.data
        if form.term.data[0] == " ":
            tempterm = form.term.data.strip()
        user_id = session.sid
        potential_full = Dictionary.query.filter(Dictionary.terminology.startswith(tempterm[0])).all()
        qt = get_inp.queue(form.term.data, potential_full, user_id)
        counter =0

        print(qt.result, "hehehe")
        looping = True
        while looping:
            try: 
                if qt.result.origterm == form.term.data:
                    looping = False
            except:
                print("zzz")

            time.sleep(1)
            print("zzz", qt.result)
            if qt.result == True:
                flashed = True
                flash('Your query has not been created, try a different acronym term!', 'danger')
                break
                
            counter = counter +1
            if counter == 5:
                flashed = True
                flash('Your query may still be pending, please refresh the page in a few seconds.', 'warning')
                break
        #qt = Job.fetch('form.term.data', rq)
        #print(qt.get_status())
        #c = False
        #while not qt.get_status() == "finished":
        #    time.sleep(0.2)
        #    print(qt.get_status())
        print(qt.result)

        if not flashed:
            flash('Your query has been created! Full Form: '+ qt.result.term, 'success')
            return redirect(url_for('queries.queryt', queryt_id=qt.result.id))
        return redirect(url_for('main.home'))
         #   check_match(abstracts, term)
    return render_template('create_queryt.html', title='New Query',
                           form=form, legend='New Query')


@queries.route("/egg/<sterm>/<termdata>", methods=['GET'])
def egg(sterm, termdata):
    user_id = session.sid
    potential_full = Dictionary.query.filter(Dictionary.terminology.startswith(sterm[0])).all()
    qt2 = get_inp.queue(sterm, potential_full, user_id, termdata)
    counter =0
    flashed = False
    looping = True

    while looping:
        print(qt2.result)
        try: 
            #print(qt2.result.origterm, sterm, "hhhh")
            if qt2.result.origterm == sterm:
                looping = False
        except:
            print("zzz")

        time.sleep(1)
        if qt2.result == True:
            flashed = True
            flash('Your query has not been created, try a different acronym term!', 'danger')
            break
                
        counter = counter +1
        if counter == 5:
            flashed = True
            flash('Your query may still be pending, please refresh the page in a few seconds.', 'warning')
            break
        #qt = Job.fetch('form.term.data', rq)
        #print(qt.get_status())
        #c = False
        #while not qt.get_status() == "finished":
        #    time.sleep(0.2)
        #    print(qt.get_status())

    if not flashed:
        flash('Your query has been created! Full Form: '+ qt2.result.term, 'success')
        return redirect(url_for('queries.queryt', queryt_id=qt2.result.id))

    return redirect(url_for('main.home'))


@queries.route("/queryt/<int:queryt_id>", methods=['GET', 'POST'])
def queryt(queryt_id):
    queryt = QueryT.query.get_or_404(queryt_id)
    articles = Article.query.filter_by(query_id=queryt_id)
    lfmatches = None
    acrmatches = None
    
    if queryt.lfmatches:
        lfmatches = queryt.lfmatches.split(", ")
    acrreplace = []
    if queryt.acrmatches:
        acrmatches = queryt.acrmatches.split(", ")
        for article in articles:
            for term in acrmatches:
                termb = "("+term+")"
                if term.lower() == queryt.origterm.lower():
                    article.abstract = article.abstract.replace(termb, '<mark class="acrmatch">'+termb+'</mark>')
                else:
                    article.abstract = article.abstract.replace(termb, '<mark class="acr">'+termb+'</mark>')
            article.abstract = Markup(article.abstract)

    form = Email()
    # def send_email(subject,sender,recipients,text_body):
    #      msg = Message(subject, sender=sender, recipients=recipients)
    #      msg.body = "hello max"
    #      mail.send(msg)

    if form.is_submitted():
        if form.validate_on_submit():
            #et = send_email("ACRPUBMED - ", ADMINS[0], [form.email.data],'hell')
            
            flash('Email Sent!', 'success')

            return redirect(url_for('queries.queryt', queryt_id=queryt.id))
        else:
            
            flash('Invalid Email!', 'danger')
            return redirect(url_for('queries.queryt', queryt_id=queryt.id))
    return render_template('queryt.html', form=form, title=queryt.term, queryt=queryt, lfmatches=lfmatches, acrmatches=acrmatches, content=articles)

     
@rq.job
def get_inp(data, potential_full, user_id, termdata=None):
    time.sleep(0.35)
    search_term, fword, abstracts, percentmatch, present, acrmatches, lfmatches, results, failed = inp(data, potential_full, termdata)
    print("done")
    queryt = QueryT(origterm=search_term, term=fword, content=abstracts, percentmatch=percentmatch,
                    origtermpresent=present, acrmatches=acrmatches, lfmatches=lfmatches, user_id=user_id)
    
    if not failed:    
        for article in results:
            abstract = article.abstract
            title = article.title
            doi = article.doi
            publication_date = article.publication_date

            queryt.author.append(Article(title=title, abstract=abstract, doi=doi, publication_date=publication_date))
        db.session.add(queryt)
        qid = queryt.id
        db.session.commit()
        print(queryt)
        return queryt
    return failed


@rq.job
def send_email(subject,sender,recipients,text_body):
    print(subject,sender,recipients,text_body)
    msg = Message(subject, sender=sender, recipients=recipients)
    msg.body=text_body
    print()
    mail.send(msg)
    return

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <main role="main" class="container col-md-10">
        <div class="content-section">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="media-body">
                    <p> Acronyms are a highly productive form of term representation. In 1970, Britton observed that “in science, new words normally emerge in response to the need for novel, precise, and economical communication” and that the acronym is a result of the “need for economy and convenience of expression … usually formed from the initials of a phrase name”. It is now rather unusual when a medical condition or procedure does not come with an associated acronym or initialism, for example, MRI (magnetic resonance imaging), ALS (amyotrophic lateral sclerosis), COPD (chronic obstructive pulmonary disease), HRT (hormone replacement therapy), and SARS (severe acute respiratory syndrome), to name a few. In an editorial lamenting the use, overuse, misuse or abuse of acronyms in medicals journals, its mentioned that in one issue of a clinical journal, fifty-two acronyms are found. Fred and Cheng go further nothing that more than ninety undefined acronyms were in one review article. Particularly in the domain of biomedical texts, this results in the challenge of identifying commonly used abbreviations’ definitions in order to keep relevant ontologies up to date. </p>
    
                    <p>Given the common use of acronyms in health sciences, researchers may be more disposed to search abbreviated terms rather than full phrases when searching online systems. Even more so when the full phrase is lengthy or difficult to spell. Searchers may also know the acronym but are ensure of its exact meaning, they may also assume that any online systems will properly translate acronyms to their corresponding full phrases automatically. Without a biomedical dictionary of acronyms and their full form definitions to hand, this too becomes a disambiguation problem. Most current methods rely on scientific writing conventions to disambiguate the full form of a given acronym. Inexplicit global abbreviations appear typically in clinical narratives without their full form definition, so cannot rely on conventions. Recognition of global acronyms usually entails mapping to a synonymous entry in an external dictionary, this can be viewed as a word sense disambiguation problem. </p>
                    <legend class="mb-4">Getting Started</legend>

                    <p>Creating a new query:</p>
                    <ol>
                        <li> Select New Query from the navigation bar.</li>
                        <li> Enter an acronym term in the input box. (Must be between 2 & 10 characters)</li>
                        <li> If the acronym could be successfully matched to a full form, a list of articles will be shown relating to this form. If the acronym could not be matched, or there were no resulting articles you will be returned to the home page.</li>
                    </ol>

                    <p>To view the results of previous queries you've made:</p>
                    <ol>
                        <li> Navigate to the home page.</li>
                        <li> Select the full form you wish to view from the list presented.</li>
                    </ol>

                    <p>If the result is not what you expected, automatic finding of the best full form for your acronym is not currently enabled. To choose another manually:</p>
                    <ol>
                        <li> Navigate to the query result page, either through the home page or through making a successful query.</li>
                        <li> Select the Potential Other Full Forms dropdown box from the analytics bar. </li>
                        <li> Select the full form you wish to query. </li>
                    </ol>

                    <p>Full forms are decided as to whether they are potential expansions of the entered acronym by distinguishing whether they would be recognised as full form if they were present together in a plaintext document following scientifc writing conventions. The veracity of this assumption is assessed by the weighting of the acronym terms defined in the resulting articles.</p>


                    <legend class="mb-4">Disclaimer</legend>
                    <p>The original documentation of the PubMed API can be found here: <a href="https://www.ncbi.nlm.nih.gov/pmc/tools/developers/">PubMed Central</a></p>
                    <p>This application is no way affiliated, associated, authorized, endorsed by, or in any way officially connected with PubMed, or any of its subsidiaries or its affiliates. The official PubMed website can be found at <a href="https://www.ncbi.nlm.nih.gov/pubmed/">https://www.ncbi.nlm.nih.gov/pubmed/</a>.</p>
                    <p>Simple algorithm used for identifying abbreviation definitions in biomedical text by <a href="https://psb.stanford.edu/psb-online/proceedings/psb03/schwartz.pdf">A. Schwartz & M. Hearst</a>.</p>
                    <p>Icons made by <a href="https://www.flaticon.com/authors/flat-icons" title="Flat Icons">Flat Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> and <a href="https://fontawesome.com/">www.fontawesome.com</a></p>
                </div>

        </div>
    </main>
{% endblock content %}



<!-- <h1>About Page</h1>
    <p>Search a term</p>
    <p>If not detected as an acronym, return abstracts for full form</p>
    <p>If detected as acronym:</p>
    <p>Select potential full forms from dictionary</p>
    <p>Find first match with S&H</p>
    <p>Search abstracts for full form</p>
    <p>For each sentence detect acronym form long form (short form), vice versa</p>
    <p>If valid short form replace long form with search term</p>
        <p>Compare search term and short term to find potential acronyms for search term with S&H</p>
    <p>Icons made by <a href="https://www.flaticon.com/authors/flat-icons" title="Flat Icons">Flat Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a></p> -->

flaskblog/templates/create_queryt.html
{% extends "layout.html" %}
{% block content %}
<main role="main" class="container col-md-10">
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.term.label(class="form-control-label") }}
                {% if form.term.errors %}
                    {{ form.term(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.term.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.term(class="form-control form-control-lg") }}
                {% endif %}
            </div>
{#            <div class="form-group">#}
{#                {{ form.content.label(class="form-control-label") }}#}
{#                {% if form.content.errors %}#}
{#                    {{ form.content(class="form-control form-control-lg is-invalid") }}#}
{#                    <div class="invalid-feedback">#}
{#                        {% for error in form.content.errors %}#}
{#                            <span>{{ error }}</span>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                {% else %}#}
{#                    {{ form.content(class="form-control form-control-lg") }}#}
{#                {% endif %}#}

        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
</main>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-fluid">
        <main role="main">
          <div class="row">
            <div class="d-flex flex-row-reverse col-md-12">
                <div id="toggler" class="btn-group btn-group-toggle p-2">
                    <label class="btn btn-secondary {{ active1 }}" onclick="location.href='{{ url_for('main.home') }}';">
                        <input type="radio" name="options" id="option1" autocomplete="off"> Recent
                    </label>
                    <label class="btn btn-secondary {{ active2 }}" onclick="location.href='{{ url_for('main.home_all') }}';">
                        <input type="radio" name="options" id="option2" autocomplete="off"> All
                    </label>
                </div>
            </div>
            <div id="mess" class="col-md-12">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
            </div>

            {% for queryt in queriest.items %}
                <article class="media content-section col-md-12">
                    <div class="media-body col-md-12">
                        <div class="article-metadata">
                            <small class="text-muted">{{ queryt.origterm }}</small>
                            <small class="text-muted"> | </small>
                            <small class="text-muted">{{ queryt.date_posted.strftime('%Y-%m-%d') }}</small>
                            <div class="rightsidediv tooltip"><!-- d-none d-sm-block  -->
                                <i class="fa fa-question-circle" style="font-size:24px"></i>
                                <span class="tooltiptext">
                                    <!-- <p>Potential Full Form of Acronym: {{ queryt.origterm }}</p>
                                    <p>{{ queryt.percentmatch }} Acronyms Detected Matched Long Form</p> -->
                                    <p>Considered Correct: {{ queryt.origtermpresent }}</p>
                                    
                                    {% if queryt.origtermpresent %}
                                        <p>Select Full Form for More Information.</p>
                                    {% else %}
                                        <p>Select Full Form for More Information or to Select Potential Correct Forms.</p>
                                    {% endif %}
                                    </p>
                                </span>
                            </div>
                        </div>
                        <h2><a class="article-title" href="{{ url_for('queries.queryt', queryt_id=queryt.id) }}">{{ queryt.term }}</a></h2>
                        <p class="article-home">{{ queryt.content }}</p>
                        <p class="cont-dash">. . .</p>
                    </div>
        {#            <img class ="align-self-center mr-3" src ="{{ url_for('static',filename=picture_file)}}">#}
                    <div class="d-none d-sm-block">
                        {% if queryt.origtermpresent %}
                            <div class = "align-self-center circleg"><p></p>{{  queryt.percentmatch }}</div>
                        {% else %}
                            <div class = "align-self-center circle"><p></p>{{  queryt.percentmatch }}</div>
                        {% endif %}
                    </div>


                </article>
            {% endfor %}
          </div>
        </main>
    </div>
{% endblock content %}
{% block footer %}

<div id="foot" class="d-flex justify-content-center col-md-12">
    {% for page_num in queriest.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if queriest.page == page_num %}
                {% if active2 %}
                    <a id = "current" class="btn btn-info mb-4" href="{{ url_for('main.home_all', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a id = "current" class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                {% if active2 %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home_all', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes, maximum-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
        <title>ACR/PUBMED - {{ title }}</title>
    {% else %}
        <title>ACR/PUBMED</title>
    {% endif %}
</head>


<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">ACR/PUBMED <i class="fa fa-bar-chart" style="font-size:26px"></i></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

                <a class="nav-item nav-link" href="{{ url_for('queries.new_queryt') }}">New Query</a>

            </div>
          </div>
        </div>
      </nav>
    </header>
{% block content %}
{% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
<footer class="page-footer fixed-bottom col-md-12">
  {% block footer %}
  {% endblock %}
</footer>
</html>

flaskblog/templates/queryt.html
{% extends "layout.html" %}
{% block content %}
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      <article class="media content-section col-md-8">

        <div class="media-body">
            {% for article in content %}

                <div class="article-metadata">
                    <small class="text-muted">{{ article.publication_date.strftime('%Y-%m-%d') }}</small>
                </div>
                    <h4 class="article-title">{{ article.title }}</h4>
                    <p class="article-content">{{ article.abstract }}</p>
                    <small>DOI:<a href="//doi.org/{{ article.doi }}">{{ article.doi }}</a></small>
                    <p></p>

            {% endfor %}
        </div>
      </article>
        <div class="col-md-4">
            <div class="content-section">
                <h3 class="text-center">Analytics bar</h3>
                <div class="row d-flex justify-content-center">
                  {% if queryt.origtermpresent %}
                    <div class="circleg "><p></p>{{  queryt.percentmatch }}</div>
                  {% else %}
                    <div class="circle"><p></p>{{  queryt.percentmatch }}</div>
                  {% endif %}
                </div>
                  <ul class="list-group text-center">
                      <li class="list-group-item list-group-item-light">Original Acronym Matched:
                        {% if queryt.origtermpresent %}
                            {{ queryt.origtermpresent }}
                        {% else %}
                            {{ queryt.origtermpresent }}
                        {% endif %}
                      </li>


                      <li class="list-group-item list-group-item-light">
                          <a data-toggle="collapse" data-target="#collapseOne" href="collapseOne">
                              Potential Other Full Forms
                          </a>
                      </li>
                      <div id = "collapseOne" class="panel-collapse collapse">

                          {% if lfmatches %}
                              <ul class="list-group list-group-flush">
                                {% for match in lfmatches %}
                                    <li class = "list-group-item"><a class="nav-item nav-link text-align-left" href="{{ url_for('queries.egg', sterm=queryt.origterm , termdata=match) }}"><small> {{ match }} </small></a></li>
                                {% endfor %}
                              </ul>
                          {% else %}
                              <ul class="list-group list-group-flush">
                                    <li class = "list-group-item"><small>N/A</small></li>
                              </ul>
                          {% endif %}
                      </div>
                      <li class="list-group-item list-group-item-light">
                          <a data-toggle="collapse" data-target="#collapseTwo" href="collapseTwo">
                              Potential Acronyms For This Full Form
                          </a>
                      </li>
                      <div id = "collapseTwo" class="panel-collapse collapse">

                          {% if acrmatches %}
                              <ul class="list-group list-group-flush">
                                {% for match in acrmatches %}
                                    <li class = "list-group-item"><a class="nav-item nav-link text-align-left" href=""><small> {{ match }} </small></a></li>
                                {% endfor %}
                              </ul>
                          {% else %}
                              <ul class="list-group list-group-flush">
                                    <li class = "list-group-item"><small>N/A</small></li>
                              </ul>
                          {% endif %}
                      </div>
                      <li class="list-group-item list-group-item-light">
                          <a data-toggle="collapse" data-target="#collapseThree" href="collapseThree">
                              Email Results
                          </a>
                      </li>
                      <div id = "collapseThree" class="panel-collapse collapse">

                          <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">

                                <div id="email" class="form-group d-flex">
                                    {% if form.email.errors %}
                                        <div class="flex-grow-1">
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        </div>
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                    {{ form.submit(class="btn btn-email btn-outline-info") }}
                                </div>
                            </fieldset>
                          </form>

                      </div>
                  </ul>
                </p>
            </div>
        </div>
      </div>
    </main>
{% endblock content %}